class UtilityRestrictions
  INCLUDE_RUNTIME = "\"includeRuntime\""
  INCLUDE_EXTENDED_RUNTIME = "\"includeExtendedRuntime\""
  INCLUDE_ELECTRICITY = "\"includeElectricity\""
  INCLUDE_SETTINGS = "\"includeSettings\""
  INCLUDE_LOCATION = "\"includeLocation\""
  INCLUDE_PROGRAM = "\"includeProgram\""
  INCLUDE_EVENTS = "\"includeEvents\""
  INCLUDE_DEVICE = "\"includeDevice\""
  INCLUDE_TECHNICIAN = "\"includeTechnician\""
  INCLUDE_UTILITY = "\"includeUtility\""
  INCLUDE_ALERTS = "\"includeAlerts\""
  INCLUDE_WEATHER = "\"includeWeather\""
  INCLUDE_OEM_CONFIG = "\"includeOemConfig\""
  INCLUDE_EQUIPMENT_STATUS = "\"includeEquipmentStatus\""
  INCLUDE_NOTIFICATION_SETTINGS = "\"includeNotificationSettings\""
  INCLUDE_PRIVACY = "\"includePrivacy\""
  INCLUDE_VERSION = "\"includeVersion\""
  INCLUDE_SECURITY_SETTINGS = "\"includeSecuritySettings\""
  INCLUDE_SENSORS = "\"includeSensors\""
end